# Site settings
name: 'CS373 Spring 2016: Moiz Rizvi'
description: 'This is a blog documenting my experience in CS 373 Software Engineering'

baseurl: '/cs373' # the subpath of your site, e.g. /blog
url: 'http://moizrizvi.github.io' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Salvatore Gentile'
    email: ''
    uri: 'https://github.com/SalGnt'

sass:
    sass_dir: _sass
    style:    compressed

 lsi: false
 safe: true
 source: moizrizvi.github.io
 incremental: false
 highlighter: rouge
 gist:
   noscript: false

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true

gems:
    - jekyll-feed
    - jekyll-sitemap
